import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "TestAdmin",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "TestCustomer",
      email: "customer@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "../images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      countInStock: 10,
      numReviews: 10,
      description: "hign quality product",
    },
    {
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "../images/p2.jpg",
      price: 100,
      countInStock: 5,
      brand: "Adidas",
      rating: 4,
      numReviews: 10,
      description: "hign quality product",
    },
    {
      name: "Lactose Free Shirt",
      category: "Shirts",
      image: "../images/p3.jpg",
      price: 120,
      countInStock: 20,
      brand: "Lactose",
      rating: 4.5,
      numReviews: 8,
      description: "hign quality product",
    },
    {
      name: "Nike Fit Pant",
      category: "Pants",
      image: "../images/p4.jpg",
      price: 180,
      countInStock: 1,
      brand: "Nike",
      rating: 4.5,
      numReviews: 6,
      description: "hign quality product",
    },
    {
      name: "Adidas Fit Pants",
      category: "Pants",
      image: "../images/p5.jpg",
      price: 120,
      countInStock: 30,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "hign quality product",
    },
    {
      name: "Puma Fit Pant",
      category: "Pants",
      image: "../images/p6.jpg",
      price: 120,
      countInStock: 0,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "hign quality product",
    },
  ],
};
export default data;
